GET http://localhost:3005/usuario

###
GET http://localhost:3005/carrito

###
POST http://localhost:3005/carrito
Content-Type: application/json

{
  
  "idusuario": 1


}
###
POST http://localhost:3005/carrito
Content-Type: application/json

{
  "idusuario": 2
}

###

GET http://localhost:3005/carrito/usuario/1

###
GET http://localhost:3005/itemcarrito/carrito/1


###
POST http://localhost:3005/itemcarrito
Content-Type: application/json

{
  "idcarrito": 1,
  "idproducto": 5,
  "cantidad": 2
}

