### Obtener todos los usuarios
GET http://localhost:3005/usuario

### Obtener un usuario por id
GET http://localhost:3005/usuario/1


### Registrar usuario (con hash + token)
POST http://localhost:3005/usuario/registrar
Content-Type: application/json

{
  "nombre": "Aiden Gamer",
  "apellido": "RADO",
  "email": "asasaaasda@assssa.com",
  "dni": "112222214",
  "password": "AidenGames",
  "telefono": "969750401",
  "direccion": "Av. Gamer 123",
  "ciudad": "Lima",
  "admin": false
}


### Login usuario (devuelve token)
POST http://localhost:3005/usuario/login
Content-Type: application/json

{
  "email": "aiden@example.com",
  "password": "AidenNuevo123"
}



PUT http://localhost:3005/usuario/3/password
Content-Type: application/json

{
  "passwordActual": "AidenGames123",
  "passwordNueva": "AidenNuevo123"
}
 