### Obtener todos los usuarios
GET http://localhost:3005/usuario

### Obtener un usuario por id
GET http://localhost:3005/usuario/1


### Registrar usuario (con hash + token)
POST http://localhost:3005/usuario/registrar
Content-Type: application/json

{
  "nombre": "Aiden",
  "apellido": "tester2",
  "email": "aprueba@example.com",
  "password": "AidenGames123",
  "dni":723
}


### Login usuario (devuelve token)
POST http://localhost:3005/usuario/login
Content-Type: application/json

{
  "email": "aiden@example.com",
  "password": "AidenNuevo123"
}


### Cambiar contraseña (usuario registrado)
# Ojo: aquí NO estamos validando token todavía, solo la contraseña actual
PUT http://localhost:3005/usuario/3/password
Content-Type: application/json

{
  "passwordActual": "AidenGames123",
  "passwordNueva": "AidenNuevo123"
}
